version: "2"
services:
  cms-utilization-db:
    image: sudowing/cms-utilization-db
    restart: always
    env_file:
      - './.env'
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data
  cms-utilization-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    ports:
      - "9200:9200"
      - "9300:9300"
    depends_on:
    - cms-utilization-db
    volumes:
      - ./volumes/elastic:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node
