version: "2"
services:
  cms-utilization-db:
    image: sudowing/cms-utilization-db
    restart: always
    env_file:
      - './.env'
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data
  cms-utilization-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    ports:
      - "9200:9200"
      - "9300:9300"
    depends_on:
    - cms-utilization-db
    volumes:
      - ./volumes/elastic:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node
  cms-utilization-api:
    image: sudowing/cms-utilization-api:develop
    ports:
      - "8042:8042"
    depends_on:
    - cms-utilization-db
    - cms-utilization-search
    env_file:
      - './.env'
    environment:
      DB_HOST: cms-utilization-db     
      DB_PORT: 5432
      ES_HOST: cms-utilization-search     
      ES_PORT: 9200
    volumes:
      - ./volumes/logs/api:/var/logs/api
