{

  suggestProviders(
    search: "marco",
    limit: 2
  ){
    npi
    entity_type
    address_city
    address_state
    gender
    name_first
    name_last
  }
  
  autocompleteServices(
    search: "High osmolar contrast material",
    limit: 3
  ){
    hcpcs_code
    hcpcs_description
    
  }
  
  geoSearch1: searchGeoProviders(
    geo: {
      top_left: {
        lon: -75.071125,
        lat: 39.971463,
      },
      bottom_right: {
        lon: -75.206823,
        lat: 39.918097,
      },
    }
  ){
    npi
    entity_type
    location{
      lat
      lon
    }
    performances{
      npi
      hcpcs_code
      n_of_svcs
      n_of_distinct_mcare_beneficiary_per_day_svcs
      n_of_mcare_beneficiaries
      avg_mcare_pay_amt
      avg_submitted_charge_amt
      avg_mcare_allowed_amt
      avg_mcare_standardized_amt
      est_ttl_mcare_pay_amt
      est_ttl_submitted_charge_amt
      mcare_participation_indicator
      place_of_service
      var_avg_mcare_submitted_charge_pay_amt
    }
  }
  

  geoSearch2: searchGeoProviders(
    geo: {
      top_left: {
        lon: -75.071125,
        lat: 39.971463,
      },
      bottom_right: {
        lon: -75.206823,
        lat: 39.918097,
      },
    },
    limit: 5
  ){
    npi
    entity_type
    location{
      lat
      lon
    }
    performances{
      npi
      hcpcs_code
      n_of_svcs
      n_of_distinct_mcare_beneficiary_per_day_svcs
      n_of_mcare_beneficiaries
      avg_mcare_pay_amt
      avg_submitted_charge_amt
      avg_mcare_allowed_amt
      avg_mcare_standardized_amt
      est_ttl_mcare_pay_amt
      est_ttl_submitted_charge_amt
      mcare_participation_indicator
      place_of_service
      var_avg_mcare_submitted_charge_pay_amt
    }
  }
  
  geoSearch3: searchGeoProviders(
    geo: {
      top_left: {
        lon: -75.071125,
        lat: 39.971463,
      },
      bottom_right: {
        lon: -75.206823,
        lat: 39.918097,
      },
    },
    service: {
      hcpcsCodes: [
        "99213",
        "J2357"
      ],
      allServices: true,
    }
    limit: 5
  ){
    npi
    entity_type
    location{
      lat
      lon
    }
    performances{
      npi
      hcpcs_code
      n_of_svcs
      n_of_distinct_mcare_beneficiary_per_day_svcs
      n_of_mcare_beneficiaries
      avg_mcare_pay_amt
      avg_submitted_charge_amt
      avg_mcare_allowed_amt
      avg_mcare_standardized_amt
      est_ttl_mcare_pay_amt
      est_ttl_submitted_charge_amt
      mcare_participation_indicator
      place_of_service
      var_avg_mcare_submitted_charge_pay_amt
    }
  }

  
  
  geoSearch4: searchGeoProviders(
    geo: {
      top_left: {
        lon: -75.071125,
        lat: 39.971463,
      },
      bottom_right: {
        lon: -75.206823,
        lat: 39.918097,
      },
    },
    service: {
      hcpcsCodes: [
        "99213",
        "J2357"
      ],
      allServices: false,
    }
    limit: 15
  ){
    npi
    entity_type
    location{
      lat
      lon
    }
    performances{
      npi
      hcpcs_code
      n_of_svcs
      n_of_distinct_mcare_beneficiary_per_day_svcs
      n_of_mcare_beneficiaries
      avg_mcare_pay_amt
      avg_submitted_charge_amt
      avg_mcare_allowed_amt
      avg_mcare_standardized_amt
      est_ttl_mcare_pay_amt
      est_ttl_submitted_charge_amt
      mcare_participation_indicator
      place_of_service
      var_avg_mcare_submitted_charge_pay_amt
    }
  }
  

  
  geoSearch6: searchGeoProviders(
    geo: {
    	location: {
        lat: 39.8707347,
        lon: -74.8982277,
    	}
    	distanceUnit: "kilometers",
    	distanceValue: 30,
    },
    service: {
      hcpcsCodes: [
        "99213",
        "J2357"
      ],
      allServices: true,
    }
    limit: 5
  ){
    npi
    entity_type
    location{
      lat
      lon
    }
    performances{
      npi
      hcpcs_code
      n_of_svcs
      n_of_distinct_mcare_beneficiary_per_day_svcs
      n_of_mcare_beneficiaries
      avg_mcare_pay_amt
      avg_submitted_charge_amt
      avg_mcare_allowed_amt
      avg_mcare_standardized_amt
      est_ttl_mcare_pay_amt
      est_ttl_submitted_charge_amt
      mcare_participation_indicator
      place_of_service
      var_avg_mcare_submitted_charge_pay_amt
    }
  }

  
  geoSearch7: searchGeoProviders(
    geo: {
    	location: {
        lat: 39.8707347,
        lon: -74.8982277,
    	}
    	distanceUnit: "miles",
    	distanceValue: 3,
    },
    service: {
      hcpcsCodes: [
        "99213",
        "J2357"
      ],
      allServices: false,
    }
    limit: 5
  ){
    npi
    entity_type
    location{
      lat
      lon
    }
    performances{
      npi
      hcpcs_code
      n_of_svcs
      n_of_distinct_mcare_beneficiary_per_day_svcs
      n_of_mcare_beneficiaries
      avg_mcare_pay_amt
      avg_submitted_charge_amt
      avg_mcare_allowed_amt
      avg_mcare_standardized_amt
      est_ttl_mcare_pay_amt
      est_ttl_submitted_charge_amt
      mcare_participation_indicator
      place_of_service
      var_avg_mcare_submitted_charge_pay_amt
    }
  }

  
  geoSearch8: searchGeoProviders(
    geo: {
    	location: {
        lat: 39.8707347,
        lon: -74.8982277,
    	}
    	distanceUnit: "miles",
    	distanceValue: 3,
    },
    service: {
      hcpcsCodes: [
        "99213",
        "J2357"
      ],
      allServices: false,
    }
    limit: 5
  ){
    npi
    entity_type
    location{
      lat
      lon
    }
    performances{
      npi
      hcpcs_code
      n_of_svcs
      n_of_distinct_mcare_beneficiary_per_day_svcs
      n_of_mcare_beneficiaries
      avg_mcare_pay_amt
      avg_submitted_charge_amt
      avg_mcare_allowed_amt
      avg_mcare_standardized_amt
      est_ttl_mcare_pay_amt
      est_ttl_submitted_charge_amt
      mcare_participation_indicator
      place_of_service
      var_avg_mcare_submitted_charge_pay_amt
    }
  }


}