{
  getProvider(npi: 1568465656){
    enumeration_type
    number
    last_updated_epoch
    created_epoch
    addresses {
      country_code
      country_name
      address_purpose
      address_type
      address_1
      address_2
      city
      state
      postal_code
      telephone_number
	  }
    taxonomies {
      code
      desc
      primary
      state
      license
	  }
    
    basic {
      name_prefix
      first_name
      last_name
      middle_name
      credential
      sole_proprietor
      gender
      enumeration_date
      last_updated
      status
      name
	  }
    identifiers {
      identifier
      code
      desc
      state
      issuer
	  }
		other_names {
      code
      type
      last_name
      first_name
      middle_name
	  }
  }
}