{

  
  
  searchGeoProviders(
    geo: {
      latitude: 39.8707347,
      longitude: -74.8982277,
      distanceUnit: "miles",
      distanceValue: 1.8,
    },
    service: {
      hcpcsCodes: [
        "99204",
        "31623",
      ],
      allServices: true,
    }
    limit: 3
  ){
    npi
    entity_type
    location{
      lat
      lon
    }
    performances{
      npi
      hcpcs_code
      n_of_svcs
      n_of_distinct_mcare_beneficiary_per_day_svcs
      n_of_mcare_beneficiaries
      avg_mcare_pay_amt
      avg_submitted_charge_amt
      avg_mcare_allowed_amt
      avg_mcare_standardized_amt
      est_ttl_mcare_pay_amt
      est_ttl_submitted_charge_amt
      mcare_participation_indicator
      place_of_service
      var_avg_mcare_submitted_charge_pay_amt
    }

  
  }
  suggestProviders(
    search: "marco",
    limit: 2
  ){
    npi
    entity_type
    address_city
    address_state
    gender
    name_first
    name_last
  }
  
  autocompleteServices(
    search: "tissue",
    limit: 3
  ){
    hcpcs_code
    hcpcs_description
    
  }
  



}